//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace HoTuanPhuoc.Models
{
    using System;
    using System.Collections.Generic;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DONDATHANGs = new HashSet<DONDATHANG>();
            this.BinhLuans = new HashSet<BinhLuan>();
        }
        [Key]
        [Required]

        public int MaKH { get; set; }

        [Required(ErrorMessage = "Họ và tên không được để trống.")]
        public string HoTen { get; set; }
        [MinLength(5, ErrorMessage = "Tên đăng nhập phải ít nhất 5 ký tự.")]
        [Required(ErrorMessage = "Tên đăng nhập không được để trống.")]

        public string TaiKhoan { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được để trống.")]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "Mật khẩu nhập lại không được để trống.")]
        [Compare("MatKhau", ErrorMessage = "Mật khẩu nhập lại phải trùng với mật khẩu")]
        public string MatKhauNL { get; set; }
        [Required(ErrorMessage = "Email không được để trống.")]
        [EmailAddress(ErrorMessage = "Email không đúng định dạng.")]

        public string Email { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được để trống.")]

        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Diện Thoại không được để trống.")]
        [StringLength(11, MinimumLength = 9, ErrorMessage = "Số điện thoại phải từ từ 9 ký tự đến 11 số")]

        public string DienThoai { get; set; }
        [Required(ErrorMessage = "Ngày sinh không được để trống.")]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}